project:
  type: website
  output-dir: docs

website:
  title: "kcschott.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: publications.qmd
        text: Publications
      - href: posts.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

